/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_client007_ndkbuild_JniKet */

#ifndef _Included_com_example_client007_ndkbuild_JniKet
#define _Included_com_example_client007_ndkbuild_JniKet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_client007_ndkbuild_JniKet
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_client007_ndkbuild_JniKet_testJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_client007_ndkbuild_JniKet
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_client007_ndkbuild_JniKet_getValue
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
